name: Replica4
services:
  neo4j4:
    image: neo4j:4.4.24
    container_name: neo4j4
    ports:
      - "7477:7474"
      - "7690:7687"
    environment:
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_AUTH: none
    ulimits:
      nofile:
        soft: 40000
        hard: 40000
    healthcheck:
      test: [ "CMD", "bash", "-c", "cypher-shell -u neo4j -p verysecretpassword 'RETURN 1'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - Replica_net_4

  app4:
    build:
      context: ../
      dockerfile: ./Dockerfiles/wrapperdockerfile
    container_name: Replica4
    ports:
      - "3003:3000"
    environment:
      DATABASE_URI: bolt://neo4j4:7687
      NEO4J_USER: "pandey"
      NEO4J_PASSWORD: "verysecretpassword"
      USER: pandey
      DATABASE: NEO4J
      LOG_LEVEL: error
      LEADER_URI: "http://Replica1:3000"
      MY_URI: "http://Replica4:3000"
    depends_on:
      neo4j4:
        condition: service_healthy
    cap_add:
       - NET_ADMIN
    networks:
      - Replica_net_4
      - Shared_net
networks:
  Replica_net_4:
  Shared_net:
    external: true
